# Основы Numpy

## Основная информация

In [2]:
import numpy as np

ndarray - основная единица в NumPy, представляет из себя n-мерный массив.

In [3]:
data: np.ndarray = np.array(
    [
        [
            [1, 2, 3],
            [4, 5, 6],
            [7, 8, 9],
        ],
        [
            [1, 2, 3],
            [4, 5, 6],
            [7, 8, 9],
        ],
        [
            [1, 2, 3],
            [4, 5, 6],
            [7, 8, 9],
        ],
    ],
)

Параметры и базовые функции:

In [4]:
# Размерность массива
shape = data.shape
print(shape)

# Кол-во измерений
dimentions = data.ndim
print(dimentions)

(3, 3, 3)
3


## Измерения в Numpy

In [5]:
# 0-D arrays - Scalars
scalar = np.array(42)
scalar2 = np.array(18)

scalar + scalar2

np.int64(60)

In [6]:
# 1-D arrays - Vectors
vec1 = np.array([1, 2, 3])
vec2 = np.array((10, 12, 16))

print(np.dot(vec1, vec2))
print(vec1 * vec2)

82
[10 24 48]


In [7]:
# 2-D arrays - Matrix
matrix = np.array(
    [
        [10, 12],
        [13, 15],
        [4, 8],
    ]
)

vec = np.array(
    [
        1, 3, 3,
    ]
)

print(*matrix, sep="\n")

# Умножение вектора на матрицу
vec @ matrix

[10 12]
[13 15]
[4 8]


array([61, 81])

In [7]:
vec2 = matrix[:, 1]
print(vec2)

vec * vec2

[12 15  8]


array([12, 45, 24])

## Минимальное кол-во измеренений

In [8]:
# Сам допаковывает переданный массив в нужное кол-во измерений

vec = np.array([1, 2], ndmin=2)
vec

array([[1, 2]])

In [9]:
array = [[1, 2, 3], [10, 12, 32]]
array = np.array(array, ndmin=2)
print(array)

[[ 1  2  3]
 [10 12 32]]


## Доступ по индексам

In [10]:
array[0, 1] + array[1, :]

array([12, 14, 34])

In [11]:
array[1, -3:-1]

array([10, 12])

## Типы данных
* Накладываются на весь массив
* Базовые типы:
    * u - безнаковые числа
    * i - целые числа
    * f - дробные числа
    * c - комплексные дробные числа
    * m - timedelta
    * M - datetime
    * S - строки
    * V - void, просто определенные куски памяти, выделенные под хранение
    * U - строки unicode
    * O - object, смешанный тип

In [12]:
array = [1, 2, 3]

numpy_array = np.array(array)
print(numpy_array.dtype, numpy_array.shape, numpy_array.ndim)


array = [1, 2, 3.]

numpy_array = np.array(array)
print(numpy_array.dtype, numpy_array.shape, numpy_array.ndim)

numpy_array = np.array(array, dtype=int)
print(numpy_array.dtype, numpy_array.shape, numpy_array.ndim)



class Test:
    def __init__(self): pass

array = [Test(), True, 3]

numpy_array = np.array(array, dtype=object)
print(numpy_array.dtype, numpy_array.shape, numpy_array.ndim)

int64 (3,) 1
float64 (3,) 1
int64 (3,) 1
object (3,) 1


Конвертация numpy массива в другой numpy массив

In [13]:
array: np.ndarray = np.array([-1.2, 2.5, 3.1])
print(array, array.dtype)

new_array = np.ndarray = array.astype("i2")
print(new_array, new_array.dtype)

[-1.2  2.5  3.1] float64
[-1  2  3] int16
